[theme]

# Primary accent for interactive elements
primaryColor = "#00C649"

# Background color for the main content area
backgroundColor = "#FFFFFF"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#F5F5F5"

# Color used for almost all text
textColor = "#2B4150"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
